using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;

namespace DynamicsEntityGenerator
{
    public class AutoGeneratorClient
    {
        private IOrganizationService _mServiceProxy;

        public AutoGeneratorClient(IOrganizationService oServiceProxy)
        {
            _mServiceProxy = oServiceProxy;
        }

        public QueryExpression NewQueryExpression<T>() where T : IAutogeneratedClass
        {
            foreach (object attribute in typeof(T).GetCustomAttributes(false))
            {
                if (attribute is TableNameAttribute)
                {
                    return new QueryExpression((attribute as TableNameAttribute).Name);
                }

            }
            return null;
        }

        public List<T> RetrieveMultiple<T>(QueryBase query) where T : new()
        {
            PropertyInfo[] properties = typeof(T).GetProperties();
            Dictionary<string, PropertyInfo> dictProp = new Dictionary<string, PropertyInfo>();
            foreach (PropertyInfo p in properties)
            {
                dictProp[p.Name] = p;
            }
            List<T> list = new List<T>();
            var results = _mServiceProxy.RetrieveMultiple(query);
            if (results != null && results.Entities != null)
            {
                foreach (var record in results.Entities)
                {
                    T item = new T();
                    ///*
                    foreach (var ac in record.Attributes)
                    {
                        if (dictProp.ContainsKey(ac.Key))
                        {
                            PropertyInfo p = dictProp[ac.Key];
                            p.SetValue(item, ac.Value.ToString());
                        }
                        else
                        {
                            Console.Error.WriteLine("Field Not Mapped! Key={0} Value={1}", ac.Key, ac.Value);
                        }
                    }
                    //*/
                    foreach (var fvc in record.FormattedValues)
                    {
                        if (dictProp.ContainsKey(fvc.Key))
                        {
                            PropertyInfo p = dictProp[fvc.Key];
                            p.SetValue(item, fvc.Value);
                        }
                        else
                        {
                            Console.Error.WriteLine("Field Not Mapped! Key={0} Value={1}", fvc.Key, fvc.Value);
                        }
                    }
                    list.Add(item);
                }
            }
            return list;
        }

        void GenerateEntity(string entity, SortedList<string, string> columns)
        {
            if (string.IsNullOrEmpty(entity) || entity.Length < 2)
            {
                return;
            }
            string ucEntity = string.Format("{0}{1}", entity.Substring(0, 1).ToUpper(), entity.Substring(1));

            string path = Path.Combine("../../Autogenerated", string.Format("{0}.cs", ucEntity));
            using (FileStream fs = File.Open(path, FileMode.Create, FileAccess.Write, FileShare.ReadWrite))
            {
                using (StreamWriter sw = new StreamWriter(fs, Encoding.UTF8))
                {
                    sw.WriteLine("[DynamicsEntityGenerator.TableName(\"{0}\")]", entity);
                    sw.WriteLine("public class {0} : DynamicsEntityGenerator.IAutogeneratedClass", ucEntity);
                    sw.WriteLine("{0}", "{");
                    foreach (var column in columns.Keys)
                    {
                        sw.WriteLine("\tpublic string {0} {1}", column, "{ get; set; }");
                    }
                    sw.WriteLine("{0}", "}");
                    sw.Flush();
                }
            }
        }

        public void GenerateClasses(string[] entities)
        {
            foreach (string entity in entities)
            {
                var query = new QueryExpression(entity);
                query.ColumnSet = new Microsoft.Xrm.Sdk.Query.ColumnSet(true);
                //query.TopCount = 1;
                var results = _mServiceProxy.RetrieveMultiple(query);
                if (results != null)
                {
                    SortedList<string, string> columns = new SortedList<string, string>();
                    foreach (var result in results.Entities)
                    {
                        foreach (string key in result.Attributes.Keys)
                        {
                            if (!columns.ContainsKey(key))
                            {
                                columns.Add(key, null);
                            }
                        }

                        /*
                        var myJSON = JsonConvert.SerializeObject(result);
                        foreach (var fvc in result.FormattedValues)
                        {
                            Console.WriteLine("Key={0} Value={1}", fvc.Key, fvc.Value);
                        }
                        */
                    }
                    GenerateEntity(entity, columns);
                }
            }
        }
    }
}
