public class Account
{
	public string accountcategorycode { get; set; }
	public string accountclassificationcode { get; set; }
	public string accountid { get; set; }
	public string accountnumber { get; set; }
	public string accountratingcode { get; set; }
	public string address1_addressid { get; set; }
	public string address1_city { get; set; }
	public string address1_composite { get; set; }
	public string address1_country { get; set; }
	public string address1_latitude { get; set; }
	public string address1_line1 { get; set; }
	public string address1_line2 { get; set; }
	public string address1_longitude { get; set; }
	public string address1_postalcode { get; set; }
	public string address1_stateorprovince { get; set; }
	public string address2_addressid { get; set; }
	public string address2_addresstypecode { get; set; }
	public string address2_freighttermscode { get; set; }
	public string address2_shippingmethodcode { get; set; }
	public string businesstypecode { get; set; }
	public string createdby { get; set; }
	public string createdon { get; set; }
	public string creditonhold { get; set; }
	public string crm_parentaccount { get; set; }
	public string crm_primarydri { get; set; }
	public string crm_secondarydri { get; set; }
	public string customersizecode { get; set; }
	public string customertypecode { get; set; }
	public string description { get; set; }
	public string donotbulkemail { get; set; }
	public string donotbulkpostalmail { get; set; }
	public string donotemail { get; set; }
	public string donotfax { get; set; }
	public string donotphone { get; set; }
	public string donotpostalmail { get; set; }
	public string donotsendmm { get; set; }
	public string emailaddress1 { get; set; }
	public string entityimage_timestamp { get; set; }
	public string entityimage_url { get; set; }
	public string entityimageid { get; set; }
	public string exchangerate { get; set; }
	public string fax { get; set; }
	public string followemail { get; set; }
	public string importsequencenumber { get; set; }
	public string industrycode { get; set; }
	public string marketingonly { get; set; }
	public string masterid { get; set; }
	public string merged { get; set; }
	public string modifiedby { get; set; }
	public string modifiedon { get; set; }
	public string msdyn_billingaccount { get; set; }
	public string msdyn_serviceterritory { get; set; }
	public string msdyn_taxexempt { get; set; }
	public string msdyn_travelchargetype { get; set; }
	public string name { get; set; }
	public string numberofemployees { get; set; }
	public string opendeals { get; set; }
	public string opendeals_date { get; set; }
	public string opendeals_state { get; set; }
	public string openrevenue { get; set; }
	public string openrevenue_base { get; set; }
	public string openrevenue_date { get; set; }
	public string openrevenue_state { get; set; }
	public string overriddencreatedon { get; set; }
	public string ownerid { get; set; }
	public string ownershipcode { get; set; }
	public string owningbusinessunit { get; set; }
	public string owninguser { get; set; }
	public string parentaccountid { get; set; }
	public string participatesinworkflow { get; set; }
	public string paymenttermscode { get; set; }
	public string preferredcontactmethodcode { get; set; }
	public string primarycontactid { get; set; }
	public string processid { get; set; }
	public string revenue { get; set; }
	public string revenue_base { get; set; }
	public string shippingmethodcode { get; set; }
	public string sic { get; set; }
	public string statecode { get; set; }
	public string statuscode { get; set; }
	public string telephone1 { get; set; }
	public string territorycode { get; set; }
	public string tickersymbol { get; set; }
	public string timezoneruleversionnumber { get; set; }
	public string transactioncurrencyid { get; set; }
	public string websiteurl { get; set; }
}
