[DynamicsEntityGenerator.TableName("account")]
public class Account : DynamicsEntityGenerator.IAutogeneratedClass
{
	[CsvHelper.Configuration.Attributes.Name("attribute_accountcategorycode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_accountcategorycode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_accountclassificationcode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_accountclassificationcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_accountid")]
	public System.Guid attribute_accountid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_accountnumber")]
	public System.String attribute_accountnumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_accountratingcode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_accountratingcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_addressid")]
	public System.Guid attribute_address1_addressid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_city")]
	public System.String attribute_address1_city { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_composite")]
	public System.String attribute_address1_composite { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_country")]
	public System.String attribute_address1_country { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_latitude")]
	public System.Double attribute_address1_latitude { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_line1")]
	public System.String attribute_address1_line1 { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_line2")]
	public System.String attribute_address1_line2 { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_longitude")]
	public System.Double attribute_address1_longitude { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_postalcode")]
	public System.String attribute_address1_postalcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_stateorprovince")]
	public System.String attribute_address1_stateorprovince { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address2_addressid")]
	public System.Guid attribute_address2_addressid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address2_addresstypecode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_address2_addresstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address2_freighttermscode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_address2_freighttermscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address2_shippingmethodcode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_address2_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_businesstypecode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_businesstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_createdby")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_createdby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_createdon")]
	public System.DateTime attribute_createdon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_creditonhold")]
	public System.Boolean attribute_creditonhold { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_crm_parentaccount")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_crm_parentaccount { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_crm_primarydri")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_crm_primarydri { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_crm_secondarydri")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_crm_secondarydri { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_customersizecode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_customersizecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_customertypecode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_customertypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_description")]
	public System.String attribute_description { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_donotbulkemail")]
	public System.Boolean attribute_donotbulkemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_donotbulkpostalmail")]
	public System.Boolean attribute_donotbulkpostalmail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_donotemail")]
	public System.Boolean attribute_donotemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_donotfax")]
	public System.Boolean attribute_donotfax { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_donotphone")]
	public System.Boolean attribute_donotphone { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_donotpostalmail")]
	public System.Boolean attribute_donotpostalmail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_donotsendmm")]
	public System.Boolean attribute_donotsendmm { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_emailaddress1")]
	public System.String attribute_emailaddress1 { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_entityimage_timestamp")]
	public System.Int64 attribute_entityimage_timestamp { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_entityimage_url")]
	public System.String attribute_entityimage_url { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_entityimageid")]
	public System.Guid attribute_entityimageid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_exchangerate")]
	public System.Decimal attribute_exchangerate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_fax")]
	public System.String attribute_fax { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_followemail")]
	public System.Boolean attribute_followemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_importsequencenumber")]
	public System.Int32 attribute_importsequencenumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_industrycode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_industrycode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_marketingonly")]
	public System.Boolean attribute_marketingonly { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_masterid")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_masterid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_merged")]
	public System.Boolean attribute_merged { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_modifiedby")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_modifiedby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_modifiedon")]
	public System.DateTime attribute_modifiedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_msdyn_billingaccount")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_msdyn_billingaccount { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_msdyn_serviceterritory")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_msdyn_serviceterritory { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_msdyn_taxexempt")]
	public System.Boolean attribute_msdyn_taxexempt { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_msdyn_travelchargetype")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_msdyn_travelchargetype { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_name")]
	public System.String attribute_name { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_numberofemployees")]
	public System.Int32 attribute_numberofemployees { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_opendeals")]
	public System.Int32 attribute_opendeals { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_opendeals_date")]
	public System.DateTime attribute_opendeals_date { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_opendeals_state")]
	public System.Int32 attribute_opendeals_state { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_openrevenue")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.Money attribute_openrevenue { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_openrevenue_base")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.Money attribute_openrevenue_base { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_openrevenue_date")]
	public System.DateTime attribute_openrevenue_date { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_openrevenue_state")]
	public System.Int32 attribute_openrevenue_state { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_overriddencreatedon")]
	public System.DateTime attribute_overriddencreatedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_ownerid")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_ownerid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_ownershipcode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_ownershipcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_owningbusinessunit")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_owningbusinessunit { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_owninguser")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_owninguser { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_parentaccountid")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_parentaccountid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_participatesinworkflow")]
	public System.Boolean attribute_participatesinworkflow { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_paymenttermscode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_paymenttermscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_preferredcontactmethodcode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_preferredcontactmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_primarycontactid")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_primarycontactid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_processid")]
	public System.Guid attribute_processid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_revenue")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.Money attribute_revenue { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_revenue_base")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.Money attribute_revenue_base { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_shippingmethodcode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_sic")]
	public System.String attribute_sic { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_statecode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_statecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_statuscode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_statuscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_telephone1")]
	public System.String attribute_telephone1 { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_territorycode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_territorycode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_tickersymbol")]
	public System.String attribute_tickersymbol { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_timezoneruleversionnumber")]
	public System.Int32 attribute_timezoneruleversionnumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_transactioncurrencyid")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_transactioncurrencyid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_websiteurl")]
	public System.String attribute_websiteurl { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_accountcategorycode")]
	public string formatted_value_accountcategorycode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_accountclassificationcode")]
	public string formatted_value_accountclassificationcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_accountratingcode")]
	public string formatted_value_accountratingcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address1_latitude")]
	public string formatted_value_address1_latitude { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address1_longitude")]
	public string formatted_value_address1_longitude { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address2_addresstypecode")]
	public string formatted_value_address2_addresstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address2_freighttermscode")]
	public string formatted_value_address2_freighttermscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address2_shippingmethodcode")]
	public string formatted_value_address2_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_businesstypecode")]
	public string formatted_value_businesstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_createdby")]
	public string formatted_value_createdby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_createdon")]
	public string formatted_value_createdon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_creditonhold")]
	public string formatted_value_creditonhold { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_crm_parentaccount")]
	public string formatted_value_crm_parentaccount { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_crm_primarydri")]
	public string formatted_value_crm_primarydri { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_crm_secondarydri")]
	public string formatted_value_crm_secondarydri { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_customersizecode")]
	public string formatted_value_customersizecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_customertypecode")]
	public string formatted_value_customertypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotbulkemail")]
	public string formatted_value_donotbulkemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotbulkpostalmail")]
	public string formatted_value_donotbulkpostalmail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotemail")]
	public string formatted_value_donotemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotfax")]
	public string formatted_value_donotfax { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotphone")]
	public string formatted_value_donotphone { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotpostalmail")]
	public string formatted_value_donotpostalmail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotsendmm")]
	public string formatted_value_donotsendmm { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_entityimage_timestamp")]
	public string formatted_value_entityimage_timestamp { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_exchangerate")]
	public string formatted_value_exchangerate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_followemail")]
	public string formatted_value_followemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_importsequencenumber")]
	public string formatted_value_importsequencenumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_industrycode")]
	public string formatted_value_industrycode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_marketingonly")]
	public string formatted_value_marketingonly { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_masterid")]
	public string formatted_value_masterid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_merged")]
	public string formatted_value_merged { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_modifiedby")]
	public string formatted_value_modifiedby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_modifiedon")]
	public string formatted_value_modifiedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_billingaccount")]
	public string formatted_value_msdyn_billingaccount { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_serviceterritory")]
	public string formatted_value_msdyn_serviceterritory { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_taxexempt")]
	public string formatted_value_msdyn_taxexempt { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_travelchargetype")]
	public string formatted_value_msdyn_travelchargetype { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_numberofemployees")]
	public string formatted_value_numberofemployees { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_opendeals")]
	public string formatted_value_opendeals { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_opendeals_date")]
	public string formatted_value_opendeals_date { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_opendeals_state")]
	public string formatted_value_opendeals_state { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_openrevenue")]
	public string formatted_value_openrevenue { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_openrevenue_base")]
	public string formatted_value_openrevenue_base { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_openrevenue_date")]
	public string formatted_value_openrevenue_date { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_openrevenue_state")]
	public string formatted_value_openrevenue_state { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_overriddencreatedon")]
	public string formatted_value_overriddencreatedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_ownerid")]
	public string formatted_value_ownerid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_ownershipcode")]
	public string formatted_value_ownershipcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_owningbusinessunit")]
	public string formatted_value_owningbusinessunit { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_parentaccountid")]
	public string formatted_value_parentaccountid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_participatesinworkflow")]
	public string formatted_value_participatesinworkflow { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_paymenttermscode")]
	public string formatted_value_paymenttermscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_preferredcontactmethodcode")]
	public string formatted_value_preferredcontactmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_primarycontactid")]
	public string formatted_value_primarycontactid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_revenue")]
	public string formatted_value_revenue { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_revenue_base")]
	public string formatted_value_revenue_base { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_shippingmethodcode")]
	public string formatted_value_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_statecode")]
	public string formatted_value_statecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_statuscode")]
	public string formatted_value_statuscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_territorycode")]
	public string formatted_value_territorycode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_timezoneruleversionnumber")]
	public string formatted_value_timezoneruleversionnumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_transactioncurrencyid")]
	public string formatted_value_transactioncurrencyid { get; set; }

}
