[DynamicsEntityGenerator.TableName("account")]
public class Account : DynamicsEntityGenerator.IAutogeneratedClass
{
	public static class Attribute
	{
		public const string accountcategorycode = "accountcategorycode";
		public const string accountclassificationcode = "accountclassificationcode";
		public const string accountid = "accountid";
		public const string accountnumber = "accountnumber";
		public const string accountratingcode = "accountratingcode";
		public const string address1_addressid = "address1_addressid";
		public const string address1_city = "address1_city";
		public const string address1_composite = "address1_composite";
		public const string address1_country = "address1_country";
		public const string address1_latitude = "address1_latitude";
		public const string address1_line1 = "address1_line1";
		public const string address1_line2 = "address1_line2";
		public const string address1_longitude = "address1_longitude";
		public const string address1_postalcode = "address1_postalcode";
		public const string address1_stateorprovince = "address1_stateorprovince";
		public const string address2_addressid = "address2_addressid";
		public const string address2_addresstypecode = "address2_addresstypecode";
		public const string address2_freighttermscode = "address2_freighttermscode";
		public const string address2_shippingmethodcode = "address2_shippingmethodcode";
		public const string businesstypecode = "businesstypecode";
		public const string createdby = "createdby";
		public const string createdon = "createdon";
		public const string creditonhold = "creditonhold";
		public const string crm_parentaccount = "crm_parentaccount";
		public const string crm_primarydri = "crm_primarydri";
		public const string crm_secondarydri = "crm_secondarydri";
		public const string customersizecode = "customersizecode";
		public const string customertypecode = "customertypecode";
		public const string description = "description";
		public const string donotbulkemail = "donotbulkemail";
		public const string donotbulkpostalmail = "donotbulkpostalmail";
		public const string donotemail = "donotemail";
		public const string donotfax = "donotfax";
		public const string donotphone = "donotphone";
		public const string donotpostalmail = "donotpostalmail";
		public const string donotsendmm = "donotsendmm";
		public const string emailaddress1 = "emailaddress1";
		public const string entityimage_timestamp = "entityimage_timestamp";
		public const string entityimage_url = "entityimage_url";
		public const string entityimageid = "entityimageid";
		public const string exchangerate = "exchangerate";
		public const string fax = "fax";
		public const string followemail = "followemail";
		public const string importsequencenumber = "importsequencenumber";
		public const string industrycode = "industrycode";
		public const string marketingonly = "marketingonly";
		public const string masterid = "masterid";
		public const string merged = "merged";
		public const string modifiedby = "modifiedby";
		public const string modifiedon = "modifiedon";
		public const string msdyn_billingaccount = "msdyn_billingaccount";
		public const string msdyn_serviceterritory = "msdyn_serviceterritory";
		public const string msdyn_taxexempt = "msdyn_taxexempt";
		public const string msdyn_travelchargetype = "msdyn_travelchargetype";
		public const string name = "name";
		public const string numberofemployees = "numberofemployees";
		public const string opendeals = "opendeals";
		public const string opendeals_date = "opendeals_date";
		public const string opendeals_state = "opendeals_state";
		public const string openrevenue = "openrevenue";
		public const string openrevenue_base = "openrevenue_base";
		public const string openrevenue_date = "openrevenue_date";
		public const string openrevenue_state = "openrevenue_state";
		public const string overriddencreatedon = "overriddencreatedon";
		public const string ownerid = "ownerid";
		public const string ownershipcode = "ownershipcode";
		public const string owningbusinessunit = "owningbusinessunit";
		public const string owninguser = "owninguser";
		public const string parentaccountid = "parentaccountid";
		public const string participatesinworkflow = "participatesinworkflow";
		public const string paymenttermscode = "paymenttermscode";
		public const string preferredcontactmethodcode = "preferredcontactmethodcode";
		public const string primarycontactid = "primarycontactid";
		public const string processid = "processid";
		public const string revenue = "revenue";
		public const string revenue_base = "revenue_base";
		public const string shippingmethodcode = "shippingmethodcode";
		public const string sic = "sic";
		public const string statecode = "statecode";
		public const string statuscode = "statuscode";
		public const string telephone1 = "telephone1";
		public const string territorycode = "territorycode";
		public const string tickersymbol = "tickersymbol";
		public const string timezoneruleversionnumber = "timezoneruleversionnumber";
		public const string transactioncurrencyid = "transactioncurrencyid";
		public const string websiteurl = "websiteurl";
	}

	[CsvHelper.Configuration.Attributes.Name("accountcategorycode")]
	public Microsoft.Xrm.Sdk.OptionSetValue accountcategorycode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("accountclassificationcode")]
	public Microsoft.Xrm.Sdk.OptionSetValue accountclassificationcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("accountid")]
	public System.Guid accountid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("accountnumber")]
	public System.String accountnumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("accountratingcode")]
	public Microsoft.Xrm.Sdk.OptionSetValue accountratingcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_addressid")]
	public System.Guid address1_addressid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_city")]
	public System.String address1_city { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_composite")]
	public System.String address1_composite { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_country")]
	public System.String address1_country { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_latitude")]
	public System.Double address1_latitude { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_line1")]
	public System.String address1_line1 { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_line2")]
	public System.String address1_line2 { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_longitude")]
	public System.Double address1_longitude { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_postalcode")]
	public System.String address1_postalcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_stateorprovince")]
	public System.String address1_stateorprovince { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address2_addressid")]
	public System.Guid address2_addressid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address2_addresstypecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue address2_addresstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address2_freighttermscode")]
	public Microsoft.Xrm.Sdk.OptionSetValue address2_freighttermscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address2_shippingmethodcode")]
	public Microsoft.Xrm.Sdk.OptionSetValue address2_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("businesstypecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue businesstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference createdby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("createdon")]
	public System.DateTime createdon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("creditonhold")]
	public System.Boolean creditonhold { get; set; }

	[CsvHelper.Configuration.Attributes.Name("crm_parentaccount")]
	public Microsoft.Xrm.Sdk.EntityReference crm_parentaccount { get; set; }

	[CsvHelper.Configuration.Attributes.Name("crm_primarydri")]
	public Microsoft.Xrm.Sdk.EntityReference crm_primarydri { get; set; }

	[CsvHelper.Configuration.Attributes.Name("crm_secondarydri")]
	public Microsoft.Xrm.Sdk.EntityReference crm_secondarydri { get; set; }

	[CsvHelper.Configuration.Attributes.Name("customersizecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue customersizecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("customertypecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue customertypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("description")]
	public System.String description { get; set; }

	[CsvHelper.Configuration.Attributes.Name("donotbulkemail")]
	public System.Boolean donotbulkemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("donotbulkpostalmail")]
	public System.Boolean donotbulkpostalmail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("donotemail")]
	public System.Boolean donotemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("donotfax")]
	public System.Boolean donotfax { get; set; }

	[CsvHelper.Configuration.Attributes.Name("donotphone")]
	public System.Boolean donotphone { get; set; }

	[CsvHelper.Configuration.Attributes.Name("donotpostalmail")]
	public System.Boolean donotpostalmail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("donotsendmm")]
	public System.Boolean donotsendmm { get; set; }

	[CsvHelper.Configuration.Attributes.Name("emailaddress1")]
	public System.String emailaddress1 { get; set; }

	[CsvHelper.Configuration.Attributes.Name("entityimage_timestamp")]
	public System.Int64 entityimage_timestamp { get; set; }

	[CsvHelper.Configuration.Attributes.Name("entityimage_url")]
	public System.String entityimage_url { get; set; }

	[CsvHelper.Configuration.Attributes.Name("entityimageid")]
	public System.Guid entityimageid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("exchangerate")]
	public System.Decimal exchangerate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("fax")]
	public System.String fax { get; set; }

	[CsvHelper.Configuration.Attributes.Name("followemail")]
	public System.Boolean followemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("importsequencenumber")]
	public System.Int32 importsequencenumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("industrycode")]
	public Microsoft.Xrm.Sdk.OptionSetValue industrycode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("marketingonly")]
	public System.Boolean marketingonly { get; set; }

	[CsvHelper.Configuration.Attributes.Name("masterid")]
	public Microsoft.Xrm.Sdk.EntityReference masterid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("merged")]
	public System.Boolean merged { get; set; }

	[CsvHelper.Configuration.Attributes.Name("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference modifiedby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("modifiedon")]
	public System.DateTime modifiedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("msdyn_billingaccount")]
	public Microsoft.Xrm.Sdk.EntityReference msdyn_billingaccount { get; set; }

	[CsvHelper.Configuration.Attributes.Name("msdyn_serviceterritory")]
	public Microsoft.Xrm.Sdk.EntityReference msdyn_serviceterritory { get; set; }

	[CsvHelper.Configuration.Attributes.Name("msdyn_taxexempt")]
	public System.Boolean msdyn_taxexempt { get; set; }

	[CsvHelper.Configuration.Attributes.Name("msdyn_travelchargetype")]
	public Microsoft.Xrm.Sdk.OptionSetValue msdyn_travelchargetype { get; set; }

	[CsvHelper.Configuration.Attributes.Name("name")]
	public System.String name { get; set; }

	[CsvHelper.Configuration.Attributes.Name("numberofemployees")]
	public System.Int32 numberofemployees { get; set; }

	[CsvHelper.Configuration.Attributes.Name("opendeals")]
	public System.Int32 opendeals { get; set; }

	[CsvHelper.Configuration.Attributes.Name("opendeals_date")]
	public System.DateTime opendeals_date { get; set; }

	[CsvHelper.Configuration.Attributes.Name("opendeals_state")]
	public System.Int32 opendeals_state { get; set; }

	[CsvHelper.Configuration.Attributes.Name("openrevenue")]
	public Microsoft.Xrm.Sdk.Money openrevenue { get; set; }

	[CsvHelper.Configuration.Attributes.Name("openrevenue_base")]
	public Microsoft.Xrm.Sdk.Money openrevenue_base { get; set; }

	[CsvHelper.Configuration.Attributes.Name("openrevenue_date")]
	public System.DateTime openrevenue_date { get; set; }

	[CsvHelper.Configuration.Attributes.Name("openrevenue_state")]
	public System.Int32 openrevenue_state { get; set; }

	[CsvHelper.Configuration.Attributes.Name("overriddencreatedon")]
	public System.DateTime overriddencreatedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference ownerid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("ownershipcode")]
	public Microsoft.Xrm.Sdk.OptionSetValue ownershipcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference owningbusinessunit { get; set; }

	[CsvHelper.Configuration.Attributes.Name("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference owninguser { get; set; }

	[CsvHelper.Configuration.Attributes.Name("parentaccountid")]
	public Microsoft.Xrm.Sdk.EntityReference parentaccountid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("participatesinworkflow")]
	public System.Boolean participatesinworkflow { get; set; }

	[CsvHelper.Configuration.Attributes.Name("paymenttermscode")]
	public Microsoft.Xrm.Sdk.OptionSetValue paymenttermscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("preferredcontactmethodcode")]
	public Microsoft.Xrm.Sdk.OptionSetValue preferredcontactmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("primarycontactid")]
	public Microsoft.Xrm.Sdk.EntityReference primarycontactid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("processid")]
	public System.Guid processid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("revenue")]
	public Microsoft.Xrm.Sdk.Money revenue { get; set; }

	[CsvHelper.Configuration.Attributes.Name("revenue_base")]
	public Microsoft.Xrm.Sdk.Money revenue_base { get; set; }

	[CsvHelper.Configuration.Attributes.Name("shippingmethodcode")]
	public Microsoft.Xrm.Sdk.OptionSetValue shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("sic")]
	public System.String sic { get; set; }

	[CsvHelper.Configuration.Attributes.Name("statecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue statecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("statuscode")]
	public Microsoft.Xrm.Sdk.OptionSetValue statuscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("telephone1")]
	public System.String telephone1 { get; set; }

	[CsvHelper.Configuration.Attributes.Name("territorycode")]
	public Microsoft.Xrm.Sdk.OptionSetValue territorycode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("tickersymbol")]
	public System.String tickersymbol { get; set; }

	[CsvHelper.Configuration.Attributes.Name("timezoneruleversionnumber")]
	public System.Int32 timezoneruleversionnumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("transactioncurrencyid")]
	public Microsoft.Xrm.Sdk.EntityReference transactioncurrencyid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("websiteurl")]
	public System.String websiteurl { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_accountcategorycode")]
	public string formatted_value_accountcategorycode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_accountclassificationcode")]
	public string formatted_value_accountclassificationcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_accountratingcode")]
	public string formatted_value_accountratingcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address1_latitude")]
	public string formatted_value_address1_latitude { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address1_longitude")]
	public string formatted_value_address1_longitude { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address2_addresstypecode")]
	public string formatted_value_address2_addresstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address2_freighttermscode")]
	public string formatted_value_address2_freighttermscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address2_shippingmethodcode")]
	public string formatted_value_address2_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_businesstypecode")]
	public string formatted_value_businesstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_createdby")]
	public string formatted_value_createdby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_createdon")]
	public string formatted_value_createdon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_creditonhold")]
	public string formatted_value_creditonhold { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_crm_parentaccount")]
	public string formatted_value_crm_parentaccount { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_crm_primarydri")]
	public string formatted_value_crm_primarydri { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_crm_secondarydri")]
	public string formatted_value_crm_secondarydri { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_customersizecode")]
	public string formatted_value_customersizecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_customertypecode")]
	public string formatted_value_customertypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotbulkemail")]
	public string formatted_value_donotbulkemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotbulkpostalmail")]
	public string formatted_value_donotbulkpostalmail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotemail")]
	public string formatted_value_donotemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotfax")]
	public string formatted_value_donotfax { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotphone")]
	public string formatted_value_donotphone { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotpostalmail")]
	public string formatted_value_donotpostalmail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotsendmm")]
	public string formatted_value_donotsendmm { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_entityimage_timestamp")]
	public string formatted_value_entityimage_timestamp { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_exchangerate")]
	public string formatted_value_exchangerate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_followemail")]
	public string formatted_value_followemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_importsequencenumber")]
	public string formatted_value_importsequencenumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_industrycode")]
	public string formatted_value_industrycode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_marketingonly")]
	public string formatted_value_marketingonly { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_masterid")]
	public string formatted_value_masterid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_merged")]
	public string formatted_value_merged { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_modifiedby")]
	public string formatted_value_modifiedby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_modifiedon")]
	public string formatted_value_modifiedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_billingaccount")]
	public string formatted_value_msdyn_billingaccount { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_serviceterritory")]
	public string formatted_value_msdyn_serviceterritory { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_taxexempt")]
	public string formatted_value_msdyn_taxexempt { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_travelchargetype")]
	public string formatted_value_msdyn_travelchargetype { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_numberofemployees")]
	public string formatted_value_numberofemployees { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_opendeals")]
	public string formatted_value_opendeals { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_opendeals_date")]
	public string formatted_value_opendeals_date { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_opendeals_state")]
	public string formatted_value_opendeals_state { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_openrevenue")]
	public string formatted_value_openrevenue { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_openrevenue_base")]
	public string formatted_value_openrevenue_base { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_openrevenue_date")]
	public string formatted_value_openrevenue_date { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_openrevenue_state")]
	public string formatted_value_openrevenue_state { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_overriddencreatedon")]
	public string formatted_value_overriddencreatedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_ownerid")]
	public string formatted_value_ownerid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_ownershipcode")]
	public string formatted_value_ownershipcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_owningbusinessunit")]
	public string formatted_value_owningbusinessunit { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_parentaccountid")]
	public string formatted_value_parentaccountid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_participatesinworkflow")]
	public string formatted_value_participatesinworkflow { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_paymenttermscode")]
	public string formatted_value_paymenttermscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_preferredcontactmethodcode")]
	public string formatted_value_preferredcontactmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_primarycontactid")]
	public string formatted_value_primarycontactid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_revenue")]
	public string formatted_value_revenue { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_revenue_base")]
	public string formatted_value_revenue_base { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_shippingmethodcode")]
	public string formatted_value_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_statecode")]
	public string formatted_value_statecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_statuscode")]
	public string formatted_value_statuscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_territorycode")]
	public string formatted_value_territorycode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_timezoneruleversionnumber")]
	public string formatted_value_timezoneruleversionnumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_transactioncurrencyid")]
	public string formatted_value_transactioncurrencyid { get; set; }

}
