[DynamicsEntityGenerator.TableName("contact")]
public class Contact : DynamicsEntityGenerator.IAutogeneratedClass
{
	[CsvHelper.Configuration.Attributes.Name("address1_addressid")]
	public System.Guid address1_addressid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_city")]
	public System.String address1_city { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_composite")]
	public System.String address1_composite { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_country")]
	public System.String address1_country { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_latitude")]
	public System.Double address1_latitude { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_line1")]
	public System.String address1_line1 { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_line2")]
	public System.String address1_line2 { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_longitude")]
	public System.Double address1_longitude { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_postalcode")]
	public System.String address1_postalcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_stateorprovince")]
	public System.String address1_stateorprovince { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address2_addressid")]
	public System.Guid address2_addressid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address2_addresstypecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue address2_addresstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address2_freighttermscode")]
	public Microsoft.Xrm.Sdk.OptionSetValue address2_freighttermscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address2_shippingmethodcode")]
	public Microsoft.Xrm.Sdk.OptionSetValue address2_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address3_addressid")]
	public System.Guid address3_addressid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("anniversary")]
	public System.DateTime anniversary { get; set; }

	[CsvHelper.Configuration.Attributes.Name("birthdate")]
	public System.DateTime birthdate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("contactid")]
	public System.Guid contactid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference createdby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("createdon")]
	public System.DateTime createdon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("creditonhold")]
	public System.Boolean creditonhold { get; set; }

	[CsvHelper.Configuration.Attributes.Name("customersizecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue customersizecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("customertypecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue customertypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("description")]
	public System.String description { get; set; }

	[CsvHelper.Configuration.Attributes.Name("donotbulkemail")]
	public System.Boolean donotbulkemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("donotbulkpostalmail")]
	public System.Boolean donotbulkpostalmail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("donotemail")]
	public System.Boolean donotemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("donotfax")]
	public System.Boolean donotfax { get; set; }

	[CsvHelper.Configuration.Attributes.Name("donotphone")]
	public System.Boolean donotphone { get; set; }

	[CsvHelper.Configuration.Attributes.Name("donotpostalmail")]
	public System.Boolean donotpostalmail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("donotsendmm")]
	public System.Boolean donotsendmm { get; set; }

	[CsvHelper.Configuration.Attributes.Name("educationcode")]
	public Microsoft.Xrm.Sdk.OptionSetValue educationcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("emailaddress1")]
	public System.String emailaddress1 { get; set; }

	[CsvHelper.Configuration.Attributes.Name("entityimage_timestamp")]
	public System.Int64 entityimage_timestamp { get; set; }

	[CsvHelper.Configuration.Attributes.Name("entityimage_url")]
	public System.String entityimage_url { get; set; }

	[CsvHelper.Configuration.Attributes.Name("entityimageid")]
	public System.Guid entityimageid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("exchangerate")]
	public System.Decimal exchangerate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("familystatuscode")]
	public Microsoft.Xrm.Sdk.OptionSetValue familystatuscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("firstname")]
	public System.String firstname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("followemail")]
	public System.Boolean followemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("fullname")]
	public System.String fullname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("gendercode")]
	public Microsoft.Xrm.Sdk.OptionSetValue gendercode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("haschildrencode")]
	public Microsoft.Xrm.Sdk.OptionSetValue haschildrencode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("importsequencenumber")]
	public System.Int32 importsequencenumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("isbackofficecustomer")]
	public System.Boolean isbackofficecustomer { get; set; }

	[CsvHelper.Configuration.Attributes.Name("jobtitle")]
	public System.String jobtitle { get; set; }

	[CsvHelper.Configuration.Attributes.Name("lastname")]
	public System.String lastname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("leadsourcecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue leadsourcecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("marketingonly")]
	public System.Boolean marketingonly { get; set; }

	[CsvHelper.Configuration.Attributes.Name("merged")]
	public System.Boolean merged { get; set; }

	[CsvHelper.Configuration.Attributes.Name("mobilephone")]
	public System.String mobilephone { get; set; }

	[CsvHelper.Configuration.Attributes.Name("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference modifiedby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("modifiedon")]
	public System.DateTime modifiedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("msdyn_gdproptout")]
	public System.Boolean msdyn_gdproptout { get; set; }

	[CsvHelper.Configuration.Attributes.Name("msdyn_orgchangestatus")]
	public Microsoft.Xrm.Sdk.OptionSetValue msdyn_orgchangestatus { get; set; }

	[CsvHelper.Configuration.Attributes.Name("nickname")]
	public System.String nickname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("overriddencreatedon")]
	public System.DateTime overriddencreatedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference ownerid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference owningbusinessunit { get; set; }

	[CsvHelper.Configuration.Attributes.Name("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference owninguser { get; set; }

	[CsvHelper.Configuration.Attributes.Name("parentcustomerid")]
	public Microsoft.Xrm.Sdk.EntityReference parentcustomerid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("participatesinworkflow")]
	public System.Boolean participatesinworkflow { get; set; }

	[CsvHelper.Configuration.Attributes.Name("preferredappointmenttimecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue preferredappointmenttimecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("preferredcontactmethodcode")]
	public Microsoft.Xrm.Sdk.OptionSetValue preferredcontactmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("shippingmethodcode")]
	public Microsoft.Xrm.Sdk.OptionSetValue shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("spousesname")]
	public System.String spousesname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("statecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue statecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("statuscode")]
	public Microsoft.Xrm.Sdk.OptionSetValue statuscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("telephone1")]
	public System.String telephone1 { get; set; }

	[CsvHelper.Configuration.Attributes.Name("territorycode")]
	public Microsoft.Xrm.Sdk.OptionSetValue territorycode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("timezoneruleversionnumber")]
	public System.Int32 timezoneruleversionnumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("transactioncurrencyid")]
	public Microsoft.Xrm.Sdk.EntityReference transactioncurrencyid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("websiteurl")]
	public System.String websiteurl { get; set; }

	[CsvHelper.Configuration.Attributes.Name("yomifullname")]
	public System.String yomifullname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address1_latitude")]
	public string formatted_value_address1_latitude { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address1_longitude")]
	public string formatted_value_address1_longitude { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address2_addresstypecode")]
	public string formatted_value_address2_addresstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address2_freighttermscode")]
	public string formatted_value_address2_freighttermscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address2_shippingmethodcode")]
	public string formatted_value_address2_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_anniversary")]
	public string formatted_value_anniversary { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_birthdate")]
	public string formatted_value_birthdate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_createdby")]
	public string formatted_value_createdby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_createdon")]
	public string formatted_value_createdon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_creditonhold")]
	public string formatted_value_creditonhold { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_customersizecode")]
	public string formatted_value_customersizecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_customertypecode")]
	public string formatted_value_customertypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotbulkemail")]
	public string formatted_value_donotbulkemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotbulkpostalmail")]
	public string formatted_value_donotbulkpostalmail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotemail")]
	public string formatted_value_donotemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotfax")]
	public string formatted_value_donotfax { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotphone")]
	public string formatted_value_donotphone { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotpostalmail")]
	public string formatted_value_donotpostalmail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotsendmm")]
	public string formatted_value_donotsendmm { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_educationcode")]
	public string formatted_value_educationcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_entityimage_timestamp")]
	public string formatted_value_entityimage_timestamp { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_exchangerate")]
	public string formatted_value_exchangerate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_familystatuscode")]
	public string formatted_value_familystatuscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_followemail")]
	public string formatted_value_followemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_gendercode")]
	public string formatted_value_gendercode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_haschildrencode")]
	public string formatted_value_haschildrencode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_importsequencenumber")]
	public string formatted_value_importsequencenumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_isbackofficecustomer")]
	public string formatted_value_isbackofficecustomer { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_leadsourcecode")]
	public string formatted_value_leadsourcecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_marketingonly")]
	public string formatted_value_marketingonly { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_merged")]
	public string formatted_value_merged { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_modifiedby")]
	public string formatted_value_modifiedby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_modifiedon")]
	public string formatted_value_modifiedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_gdproptout")]
	public string formatted_value_msdyn_gdproptout { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_orgchangestatus")]
	public string formatted_value_msdyn_orgchangestatus { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_overriddencreatedon")]
	public string formatted_value_overriddencreatedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_ownerid")]
	public string formatted_value_ownerid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_owningbusinessunit")]
	public string formatted_value_owningbusinessunit { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_parentcustomerid")]
	public string formatted_value_parentcustomerid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_participatesinworkflow")]
	public string formatted_value_participatesinworkflow { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_preferredappointmenttimecode")]
	public string formatted_value_preferredappointmenttimecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_preferredcontactmethodcode")]
	public string formatted_value_preferredcontactmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_shippingmethodcode")]
	public string formatted_value_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_statecode")]
	public string formatted_value_statecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_statuscode")]
	public string formatted_value_statuscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_territorycode")]
	public string formatted_value_territorycode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_timezoneruleversionnumber")]
	public string formatted_value_timezoneruleversionnumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_transactioncurrencyid")]
	public string formatted_value_transactioncurrencyid { get; set; }

}
