[DynamicsEntityGenerator.TableName("contact")]
public class Contact : DynamicsEntityGenerator.IAutogeneratedClass
{
	[CsvHelper.Configuration.Attributes.Name("attribute_address1_addressid")]
	public System.Guid attribute_address1_addressid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_city")]
	public System.String attribute_address1_city { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_composite")]
	public System.String attribute_address1_composite { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_country")]
	public System.String attribute_address1_country { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_latitude")]
	public System.Double attribute_address1_latitude { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_line1")]
	public System.String attribute_address1_line1 { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_line2")]
	public System.String attribute_address1_line2 { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_longitude")]
	public System.Double attribute_address1_longitude { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_postalcode")]
	public System.String attribute_address1_postalcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_stateorprovince")]
	public System.String attribute_address1_stateorprovince { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address2_addressid")]
	public System.Guid attribute_address2_addressid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address2_addresstypecode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_address2_addresstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address2_addresstypecode.Value")]
	public System.String attribute_address2_addresstypecode_value { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address2_freighttermscode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_address2_freighttermscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address2_freighttermscode.Value")]
	public System.String attribute_address2_freighttermscode_value { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address2_shippingmethodcode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_address2_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address2_shippingmethodcode.Value")]
	public System.String attribute_address2_shippingmethodcode_value { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address3_addressid")]
	public System.Guid attribute_address3_addressid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_anniversary")]
	public System.DateTime attribute_anniversary { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_birthdate")]
	public System.DateTime attribute_birthdate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_contactid")]
	public System.Guid attribute_contactid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_createdby")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_createdby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_createdby.Id")]
	public System.String attribute_createdby_id { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_createdby.LogicalName")]
	public System.String attribute_createdby_logical_name { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_createdby.Name")]
	public System.String attribute_createdby_name { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_createdon")]
	public System.DateTime attribute_createdon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_creditonhold")]
	public System.Boolean attribute_creditonhold { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_customersizecode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_customersizecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_customersizecode.Value")]
	public System.String attribute_customersizecode_value { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_customertypecode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_customertypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_customertypecode.Value")]
	public System.String attribute_customertypecode_value { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_description")]
	public System.String attribute_description { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_donotbulkemail")]
	public System.Boolean attribute_donotbulkemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_donotbulkpostalmail")]
	public System.Boolean attribute_donotbulkpostalmail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_donotemail")]
	public System.Boolean attribute_donotemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_donotfax")]
	public System.Boolean attribute_donotfax { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_donotphone")]
	public System.Boolean attribute_donotphone { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_donotpostalmail")]
	public System.Boolean attribute_donotpostalmail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_donotsendmm")]
	public System.Boolean attribute_donotsendmm { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_educationcode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_educationcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_educationcode.Value")]
	public System.String attribute_educationcode_value { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_emailaddress1")]
	public System.String attribute_emailaddress1 { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_entityimage_timestamp")]
	public System.Int64 attribute_entityimage_timestamp { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_entityimage_url")]
	public System.String attribute_entityimage_url { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_entityimageid")]
	public System.Guid attribute_entityimageid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_exchangerate")]
	public System.Decimal attribute_exchangerate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_familystatuscode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_familystatuscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_familystatuscode.Value")]
	public System.String attribute_familystatuscode_value { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_firstname")]
	public System.String attribute_firstname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_followemail")]
	public System.Boolean attribute_followemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_fullname")]
	public System.String attribute_fullname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_gendercode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_gendercode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_gendercode.Value")]
	public System.String attribute_gendercode_value { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_haschildrencode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_haschildrencode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_haschildrencode.Value")]
	public System.String attribute_haschildrencode_value { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_importsequencenumber")]
	public System.Int32 attribute_importsequencenumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_isbackofficecustomer")]
	public System.Boolean attribute_isbackofficecustomer { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_jobtitle")]
	public System.String attribute_jobtitle { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_lastname")]
	public System.String attribute_lastname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_leadsourcecode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_leadsourcecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_leadsourcecode.Value")]
	public System.String attribute_leadsourcecode_value { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_marketingonly")]
	public System.Boolean attribute_marketingonly { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_merged")]
	public System.Boolean attribute_merged { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_mobilephone")]
	public System.String attribute_mobilephone { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_modifiedby")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_modifiedby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_modifiedby.Id")]
	public System.String attribute_modifiedby_id { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_modifiedby.LogicalName")]
	public System.String attribute_modifiedby_logical_name { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_modifiedby.Name")]
	public System.String attribute_modifiedby_name { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_modifiedon")]
	public System.DateTime attribute_modifiedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_msdyn_gdproptout")]
	public System.Boolean attribute_msdyn_gdproptout { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_msdyn_orgchangestatus")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_msdyn_orgchangestatus { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_msdyn_orgchangestatus.Value")]
	public System.String attribute_msdyn_orgchangestatus_value { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_nickname")]
	public System.String attribute_nickname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_overriddencreatedon")]
	public System.DateTime attribute_overriddencreatedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_ownerid")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_ownerid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_ownerid.Id")]
	public System.String attribute_ownerid_id { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_ownerid.LogicalName")]
	public System.String attribute_ownerid_logical_name { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_ownerid.Name")]
	public System.String attribute_ownerid_name { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_owningbusinessunit")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_owningbusinessunit { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_owningbusinessunit.Id")]
	public System.String attribute_owningbusinessunit_id { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_owningbusinessunit.LogicalName")]
	public System.String attribute_owningbusinessunit_logical_name { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_owningbusinessunit.Name")]
	public System.String attribute_owningbusinessunit_name { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_owninguser")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_owninguser { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_owninguser.Id")]
	public System.String attribute_owninguser_id { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_owninguser.LogicalName")]
	public System.String attribute_owninguser_logical_name { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_owninguser.Name")]
	public System.String attribute_owninguser_name { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_parentcustomerid")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_parentcustomerid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_parentcustomerid.Id")]
	public System.String attribute_parentcustomerid_id { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_parentcustomerid.LogicalName")]
	public System.String attribute_parentcustomerid_logical_name { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_parentcustomerid.Name")]
	public System.String attribute_parentcustomerid_name { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_participatesinworkflow")]
	public System.Boolean attribute_participatesinworkflow { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_preferredappointmenttimecode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_preferredappointmenttimecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_preferredappointmenttimecode.Value")]
	public System.String attribute_preferredappointmenttimecode_value { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_preferredcontactmethodcode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_preferredcontactmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_preferredcontactmethodcode.Value")]
	public System.String attribute_preferredcontactmethodcode_value { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_shippingmethodcode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_shippingmethodcode.Value")]
	public System.String attribute_shippingmethodcode_value { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_spousesname")]
	public System.String attribute_spousesname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_statecode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_statecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_statecode.Value")]
	public System.String attribute_statecode_value { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_statuscode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_statuscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_statuscode.Value")]
	public System.String attribute_statuscode_value { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_telephone1")]
	public System.String attribute_telephone1 { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_territorycode")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_territorycode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_territorycode.Value")]
	public System.String attribute_territorycode_value { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_timezoneruleversionnumber")]
	public System.Int32 attribute_timezoneruleversionnumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_transactioncurrencyid")]
	[CsvHelper.Configuration.Attributes.Ignore]
	public Microsoft.Xrm.Sdk.EntityReference attribute_transactioncurrencyid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_transactioncurrencyid.Id")]
	public System.String attribute_transactioncurrencyid_id { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_transactioncurrencyid.LogicalName")]
	public System.String attribute_transactioncurrencyid_logical_name { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_transactioncurrencyid.Name")]
	public System.String attribute_transactioncurrencyid_name { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_websiteurl")]
	public System.String attribute_websiteurl { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_yomifullname")]
	public System.String attribute_yomifullname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address1_latitude")]
	public string formatted_value_address1_latitude { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address1_longitude")]
	public string formatted_value_address1_longitude { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address2_addresstypecode")]
	public string formatted_value_address2_addresstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address2_freighttermscode")]
	public string formatted_value_address2_freighttermscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address2_shippingmethodcode")]
	public string formatted_value_address2_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_anniversary")]
	public string formatted_value_anniversary { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_birthdate")]
	public string formatted_value_birthdate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_createdby")]
	public string formatted_value_createdby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_createdon")]
	public string formatted_value_createdon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_creditonhold")]
	public string formatted_value_creditonhold { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_customersizecode")]
	public string formatted_value_customersizecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_customertypecode")]
	public string formatted_value_customertypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotbulkemail")]
	public string formatted_value_donotbulkemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotbulkpostalmail")]
	public string formatted_value_donotbulkpostalmail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotemail")]
	public string formatted_value_donotemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotfax")]
	public string formatted_value_donotfax { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotphone")]
	public string formatted_value_donotphone { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotpostalmail")]
	public string formatted_value_donotpostalmail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_donotsendmm")]
	public string formatted_value_donotsendmm { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_educationcode")]
	public string formatted_value_educationcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_entityimage_timestamp")]
	public string formatted_value_entityimage_timestamp { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_exchangerate")]
	public string formatted_value_exchangerate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_familystatuscode")]
	public string formatted_value_familystatuscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_followemail")]
	public string formatted_value_followemail { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_gendercode")]
	public string formatted_value_gendercode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_haschildrencode")]
	public string formatted_value_haschildrencode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_importsequencenumber")]
	public string formatted_value_importsequencenumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_isbackofficecustomer")]
	public string formatted_value_isbackofficecustomer { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_leadsourcecode")]
	public string formatted_value_leadsourcecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_marketingonly")]
	public string formatted_value_marketingonly { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_merged")]
	public string formatted_value_merged { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_modifiedby")]
	public string formatted_value_modifiedby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_modifiedon")]
	public string formatted_value_modifiedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_gdproptout")]
	public string formatted_value_msdyn_gdproptout { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_orgchangestatus")]
	public string formatted_value_msdyn_orgchangestatus { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_overriddencreatedon")]
	public string formatted_value_overriddencreatedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_ownerid")]
	public string formatted_value_ownerid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_owningbusinessunit")]
	public string formatted_value_owningbusinessunit { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_parentcustomerid")]
	public string formatted_value_parentcustomerid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_participatesinworkflow")]
	public string formatted_value_participatesinworkflow { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_preferredappointmenttimecode")]
	public string formatted_value_preferredappointmenttimecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_preferredcontactmethodcode")]
	public string formatted_value_preferredcontactmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_shippingmethodcode")]
	public string formatted_value_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_statecode")]
	public string formatted_value_statecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_statuscode")]
	public string formatted_value_statuscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_territorycode")]
	public string formatted_value_territorycode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_timezoneruleversionnumber")]
	public string formatted_value_timezoneruleversionnumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_transactioncurrencyid")]
	public string formatted_value_transactioncurrencyid { get; set; }

}
