[DynamicsEntityGenerator.TableName("systemuser")]
public class Systemuser : DynamicsEntityGenerator.IAutogeneratedClass
{
	[CsvHelper.Configuration.Attributes.Name("attribute_accessmode")]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_accessmode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_addressid")]
	public System.Guid attribute_address1_addressid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_addresstypecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_address1_addresstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_composite")]
	public System.String attribute_address1_composite { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_country")]
	public System.String attribute_address1_country { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address1_shippingmethodcode")]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_address1_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address2_addressid")]
	public System.Guid attribute_address2_addressid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address2_addresstypecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_address2_addresstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_address2_shippingmethodcode")]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_address2_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_applicationid")]
	public System.Guid attribute_applicationid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_applicationiduri")]
	public System.String attribute_applicationiduri { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_azureactivedirectoryobjectid")]
	public System.Guid attribute_azureactivedirectoryobjectid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_businessunitid")]
	public Microsoft.Xrm.Sdk.EntityReference attribute_businessunitid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_calendarid")]
	public Microsoft.Xrm.Sdk.EntityReference attribute_calendarid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_caltype")]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_caltype { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_createdby")]
	public Microsoft.Xrm.Sdk.EntityReference attribute_createdby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_createdon")]
	public System.DateTime attribute_createdon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_defaultfilterspopulated")]
	public System.Boolean attribute_defaultfilterspopulated { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_defaultmailbox")]
	public Microsoft.Xrm.Sdk.EntityReference attribute_defaultmailbox { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_defaultodbfoldername")]
	public System.String attribute_defaultodbfoldername { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_deletedstate")]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_deletedstate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_displayinserviceviews")]
	public System.Boolean attribute_displayinserviceviews { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_domainname")]
	public System.String attribute_domainname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_emailrouteraccessapproval")]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_emailrouteraccessapproval { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_exchangerate")]
	public System.Decimal attribute_exchangerate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_firstname")]
	public System.String attribute_firstname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_fullname")]
	public System.String attribute_fullname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_identityid")]
	public System.Int32 attribute_identityid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_incomingemaildeliverymethod")]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_incomingemaildeliverymethod { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_internalemailaddress")]
	public System.String attribute_internalemailaddress { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_invitestatuscode")]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_invitestatuscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_isdisabled")]
	public System.Boolean attribute_isdisabled { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_isemailaddressapprovedbyo365admin")]
	public System.Boolean attribute_isemailaddressapprovedbyo365admin { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_isintegrationuser")]
	public System.Boolean attribute_isintegrationuser { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_islicensed")]
	public System.Boolean attribute_islicensed { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_issyncwithdirectory")]
	public System.Boolean attribute_issyncwithdirectory { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_lastname")]
	public System.String attribute_lastname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference attribute_modifiedby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_modifiedon")]
	public System.DateTime attribute_modifiedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference attribute_modifiedonbehalfby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_msdyn_agentType")]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_msdyn_agentType { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_msdyn_botprovider")]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_msdyn_botprovider { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_msdyn_capacity")]
	public System.Int32 attribute_msdyn_capacity { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_msdyn_defaultpresenceiduser")]
	public Microsoft.Xrm.Sdk.EntityReference attribute_msdyn_defaultpresenceiduser { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_msdyn_gdproptout")]
	public System.Boolean attribute_msdyn_gdproptout { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_msdyn_usertype")]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_msdyn_usertype { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_organizationid")]
	public System.Guid attribute_organizationid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_outgoingemaildeliverymethod")]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_outgoingemaildeliverymethod { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_preferredaddresscode")]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_preferredaddresscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_preferredemailcode")]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_preferredemailcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_preferredphonecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue attribute_preferredphonecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_queueid")]
	public Microsoft.Xrm.Sdk.EntityReference attribute_queueid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_setupuser")]
	public System.Boolean attribute_setupuser { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_systemuserid")]
	public System.Guid attribute_systemuserid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_transactioncurrencyid")]
	public Microsoft.Xrm.Sdk.EntityReference attribute_transactioncurrencyid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_userlicensetype")]
	public System.Int32 attribute_userlicensetype { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_userpuid")]
	public System.String attribute_userpuid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_windowsliveid")]
	public System.String attribute_windowsliveid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("attribute_yomifullname")]
	public System.String attribute_yomifullname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_accessmode")]
	public string formatted_value_accessmode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address1_addresstypecode")]
	public string formatted_value_address1_addresstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address1_shippingmethodcode")]
	public string formatted_value_address1_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address2_addresstypecode")]
	public string formatted_value_address2_addresstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address2_shippingmethodcode")]
	public string formatted_value_address2_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_businessunitid")]
	public string formatted_value_businessunitid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_caltype")]
	public string formatted_value_caltype { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_createdby")]
	public string formatted_value_createdby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_createdon")]
	public string formatted_value_createdon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_defaultfilterspopulated")]
	public string formatted_value_defaultfilterspopulated { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_defaultmailbox")]
	public string formatted_value_defaultmailbox { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_deletedstate")]
	public string formatted_value_deletedstate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_displayinserviceviews")]
	public string formatted_value_displayinserviceviews { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_emailrouteraccessapproval")]
	public string formatted_value_emailrouteraccessapproval { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_exchangerate")]
	public string formatted_value_exchangerate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_identityid")]
	public string formatted_value_identityid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_incomingemaildeliverymethod")]
	public string formatted_value_incomingemaildeliverymethod { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_invitestatuscode")]
	public string formatted_value_invitestatuscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_isdisabled")]
	public string formatted_value_isdisabled { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_isemailaddressapprovedbyo365admin")]
	public string formatted_value_isemailaddressapprovedbyo365admin { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_isintegrationuser")]
	public string formatted_value_isintegrationuser { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_islicensed")]
	public string formatted_value_islicensed { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_issyncwithdirectory")]
	public string formatted_value_issyncwithdirectory { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_modifiedby")]
	public string formatted_value_modifiedby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_modifiedon")]
	public string formatted_value_modifiedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_modifiedonbehalfby")]
	public string formatted_value_modifiedonbehalfby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_agentType")]
	public string formatted_value_msdyn_agentType { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_botprovider")]
	public string formatted_value_msdyn_botprovider { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_capacity")]
	public string formatted_value_msdyn_capacity { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_defaultpresenceiduser")]
	public string formatted_value_msdyn_defaultpresenceiduser { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_gdproptout")]
	public string formatted_value_msdyn_gdproptout { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_usertype")]
	public string formatted_value_msdyn_usertype { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_outgoingemaildeliverymethod")]
	public string formatted_value_outgoingemaildeliverymethod { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_preferredaddresscode")]
	public string formatted_value_preferredaddresscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_preferredemailcode")]
	public string formatted_value_preferredemailcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_preferredphonecode")]
	public string formatted_value_preferredphonecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_queueid")]
	public string formatted_value_queueid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_setupuser")]
	public string formatted_value_setupuser { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_transactioncurrencyid")]
	public string formatted_value_transactioncurrencyid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_userlicensetype")]
	public string formatted_value_userlicensetype { get; set; }

}
