[DynamicsEntityGenerator.TableName("systemuser")]
public class Systemuser : DynamicsEntityGenerator.IAutogeneratedClass
{
	[CsvHelper.Configuration.Attributes.Name("accessmode")]
	public Microsoft.Xrm.Sdk.OptionSetValue accessmode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_addressid")]
	public System.Guid address1_addressid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_addresstypecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue address1_addresstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_composite")]
	public System.String address1_composite { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_country")]
	public System.String address1_country { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address1_shippingmethodcode")]
	public Microsoft.Xrm.Sdk.OptionSetValue address1_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address2_addressid")]
	public System.Guid address2_addressid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address2_addresstypecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue address2_addresstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("address2_shippingmethodcode")]
	public Microsoft.Xrm.Sdk.OptionSetValue address2_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("applicationid")]
	public System.Guid applicationid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("applicationiduri")]
	public System.String applicationiduri { get; set; }

	[CsvHelper.Configuration.Attributes.Name("azureactivedirectoryobjectid")]
	public System.Guid azureactivedirectoryobjectid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("businessunitid")]
	public Microsoft.Xrm.Sdk.EntityReference businessunitid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("calendarid")]
	public Microsoft.Xrm.Sdk.EntityReference calendarid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("caltype")]
	public Microsoft.Xrm.Sdk.OptionSetValue caltype { get; set; }

	[CsvHelper.Configuration.Attributes.Name("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference createdby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("createdon")]
	public System.DateTime createdon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("defaultfilterspopulated")]
	public System.Boolean defaultfilterspopulated { get; set; }

	[CsvHelper.Configuration.Attributes.Name("defaultmailbox")]
	public Microsoft.Xrm.Sdk.EntityReference defaultmailbox { get; set; }

	[CsvHelper.Configuration.Attributes.Name("defaultodbfoldername")]
	public System.String defaultodbfoldername { get; set; }

	[CsvHelper.Configuration.Attributes.Name("deletedstate")]
	public Microsoft.Xrm.Sdk.OptionSetValue deletedstate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("displayinserviceviews")]
	public System.Boolean displayinserviceviews { get; set; }

	[CsvHelper.Configuration.Attributes.Name("domainname")]
	public System.String domainname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("emailrouteraccessapproval")]
	public Microsoft.Xrm.Sdk.OptionSetValue emailrouteraccessapproval { get; set; }

	[CsvHelper.Configuration.Attributes.Name("exchangerate")]
	public System.Decimal exchangerate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("firstname")]
	public System.String firstname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("fullname")]
	public System.String fullname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("identityid")]
	public System.Int32 identityid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("incomingemaildeliverymethod")]
	public Microsoft.Xrm.Sdk.OptionSetValue incomingemaildeliverymethod { get; set; }

	[CsvHelper.Configuration.Attributes.Name("internalemailaddress")]
	public System.String internalemailaddress { get; set; }

	[CsvHelper.Configuration.Attributes.Name("invitestatuscode")]
	public Microsoft.Xrm.Sdk.OptionSetValue invitestatuscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("isdisabled")]
	public System.Boolean isdisabled { get; set; }

	[CsvHelper.Configuration.Attributes.Name("isemailaddressapprovedbyo365admin")]
	public System.Boolean isemailaddressapprovedbyo365admin { get; set; }

	[CsvHelper.Configuration.Attributes.Name("isintegrationuser")]
	public System.Boolean isintegrationuser { get; set; }

	[CsvHelper.Configuration.Attributes.Name("islicensed")]
	public System.Boolean islicensed { get; set; }

	[CsvHelper.Configuration.Attributes.Name("issyncwithdirectory")]
	public System.Boolean issyncwithdirectory { get; set; }

	[CsvHelper.Configuration.Attributes.Name("lastname")]
	public System.String lastname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference modifiedby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("modifiedon")]
	public System.DateTime modifiedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference modifiedonbehalfby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("msdyn_agentType")]
	public Microsoft.Xrm.Sdk.OptionSetValue msdyn_agentType { get; set; }

	[CsvHelper.Configuration.Attributes.Name("msdyn_botprovider")]
	public Microsoft.Xrm.Sdk.OptionSetValue msdyn_botprovider { get; set; }

	[CsvHelper.Configuration.Attributes.Name("msdyn_capacity")]
	public System.Int32 msdyn_capacity { get; set; }

	[CsvHelper.Configuration.Attributes.Name("msdyn_defaultpresenceiduser")]
	public Microsoft.Xrm.Sdk.EntityReference msdyn_defaultpresenceiduser { get; set; }

	[CsvHelper.Configuration.Attributes.Name("msdyn_gdproptout")]
	public System.Boolean msdyn_gdproptout { get; set; }

	[CsvHelper.Configuration.Attributes.Name("msdyn_usertype")]
	public Microsoft.Xrm.Sdk.OptionSetValue msdyn_usertype { get; set; }

	[CsvHelper.Configuration.Attributes.Name("organizationid")]
	public System.Guid organizationid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("outgoingemaildeliverymethod")]
	public Microsoft.Xrm.Sdk.OptionSetValue outgoingemaildeliverymethod { get; set; }

	[CsvHelper.Configuration.Attributes.Name("preferredaddresscode")]
	public Microsoft.Xrm.Sdk.OptionSetValue preferredaddresscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("preferredemailcode")]
	public Microsoft.Xrm.Sdk.OptionSetValue preferredemailcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("preferredphonecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue preferredphonecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("queueid")]
	public Microsoft.Xrm.Sdk.EntityReference queueid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("setupuser")]
	public System.Boolean setupuser { get; set; }

	[CsvHelper.Configuration.Attributes.Name("systemuserid")]
	public System.Guid systemuserid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("transactioncurrencyid")]
	public Microsoft.Xrm.Sdk.EntityReference transactioncurrencyid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("userlicensetype")]
	public System.Int32 userlicensetype { get; set; }

	[CsvHelper.Configuration.Attributes.Name("userpuid")]
	public System.String userpuid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("windowsliveid")]
	public System.String windowsliveid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("yomifullname")]
	public System.String yomifullname { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_accessmode")]
	public string formatted_value_accessmode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address1_addresstypecode")]
	public string formatted_value_address1_addresstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address1_shippingmethodcode")]
	public string formatted_value_address1_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address2_addresstypecode")]
	public string formatted_value_address2_addresstypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_address2_shippingmethodcode")]
	public string formatted_value_address2_shippingmethodcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_businessunitid")]
	public string formatted_value_businessunitid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_caltype")]
	public string formatted_value_caltype { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_createdby")]
	public string formatted_value_createdby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_createdon")]
	public string formatted_value_createdon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_defaultfilterspopulated")]
	public string formatted_value_defaultfilterspopulated { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_defaultmailbox")]
	public string formatted_value_defaultmailbox { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_deletedstate")]
	public string formatted_value_deletedstate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_displayinserviceviews")]
	public string formatted_value_displayinserviceviews { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_emailrouteraccessapproval")]
	public string formatted_value_emailrouteraccessapproval { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_exchangerate")]
	public string formatted_value_exchangerate { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_identityid")]
	public string formatted_value_identityid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_incomingemaildeliverymethod")]
	public string formatted_value_incomingemaildeliverymethod { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_invitestatuscode")]
	public string formatted_value_invitestatuscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_isdisabled")]
	public string formatted_value_isdisabled { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_isemailaddressapprovedbyo365admin")]
	public string formatted_value_isemailaddressapprovedbyo365admin { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_isintegrationuser")]
	public string formatted_value_isintegrationuser { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_islicensed")]
	public string formatted_value_islicensed { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_issyncwithdirectory")]
	public string formatted_value_issyncwithdirectory { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_modifiedby")]
	public string formatted_value_modifiedby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_modifiedon")]
	public string formatted_value_modifiedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_modifiedonbehalfby")]
	public string formatted_value_modifiedonbehalfby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_agentType")]
	public string formatted_value_msdyn_agentType { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_botprovider")]
	public string formatted_value_msdyn_botprovider { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_capacity")]
	public string formatted_value_msdyn_capacity { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_defaultpresenceiduser")]
	public string formatted_value_msdyn_defaultpresenceiduser { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_gdproptout")]
	public string formatted_value_msdyn_gdproptout { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_msdyn_usertype")]
	public string formatted_value_msdyn_usertype { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_outgoingemaildeliverymethod")]
	public string formatted_value_outgoingemaildeliverymethod { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_preferredaddresscode")]
	public string formatted_value_preferredaddresscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_preferredemailcode")]
	public string formatted_value_preferredemailcode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_preferredphonecode")]
	public string formatted_value_preferredphonecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_queueid")]
	public string formatted_value_queueid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_setupuser")]
	public string formatted_value_setupuser { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_transactioncurrencyid")]
	public string formatted_value_transactioncurrencyid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_userlicensetype")]
	public string formatted_value_userlicensetype { get; set; }

}
