[DynamicsEntityGenerator.TableName("task")]
public class Task : DynamicsEntityGenerator.IAutogeneratedClass
{
	public static class Attribute
	{
		public const string activityid = "activityid";
		public const string activitytypecode = "activitytypecode";
		public const string actualdurationminutes = "actualdurationminutes";
		public const string actualstart = "actualstart";
		public const string createdby = "createdby";
		public const string createdon = "createdon";
		public const string crm_outlooktaskid = "crm_outlooktaskid";
		public const string description = "description";
		public const string isbilled = "isbilled";
		public const string isregularactivity = "isregularactivity";
		public const string isworkflowcreated = "isworkflowcreated";
		public const string modifiedby = "modifiedby";
		public const string modifiedon = "modifiedon";
		public const string ownerid = "ownerid";
		public const string owningbusinessunit = "owningbusinessunit";
		public const string owninguser = "owninguser";
		public const string percentcomplete = "percentcomplete";
		public const string prioritycode = "prioritycode";
		public const string processid = "processid";
		public const string regardingobjectid = "regardingobjectid";
		public const string scheduleddurationminutes = "scheduleddurationminutes";
		public const string scheduledend = "scheduledend";
		public const string scheduledstart = "scheduledstart";
		public const string statecode = "statecode";
		public const string statuscode = "statuscode";
		public const string subject = "subject";
		public const string timezoneruleversionnumber = "timezoneruleversionnumber";
	}

	[CsvHelper.Configuration.Attributes.Name("activityid")]
	public System.Guid activityid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("activitytypecode")]
	public System.String activitytypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("actualdurationminutes")]
	public System.Int32 actualdurationminutes { get; set; }

	[CsvHelper.Configuration.Attributes.Name("actualstart")]
	public System.DateTime actualstart { get; set; }

	[CsvHelper.Configuration.Attributes.Name("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference createdby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("createdon")]
	public System.DateTime createdon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("crm_outlooktaskid")]
	public System.String crm_outlooktaskid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("description")]
	public System.String description { get; set; }

	[CsvHelper.Configuration.Attributes.Name("isbilled")]
	public System.Boolean isbilled { get; set; }

	[CsvHelper.Configuration.Attributes.Name("isregularactivity")]
	public System.Boolean isregularactivity { get; set; }

	[CsvHelper.Configuration.Attributes.Name("isworkflowcreated")]
	public System.Boolean isworkflowcreated { get; set; }

	[CsvHelper.Configuration.Attributes.Name("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference modifiedby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("modifiedon")]
	public System.DateTime modifiedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference ownerid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference owningbusinessunit { get; set; }

	[CsvHelper.Configuration.Attributes.Name("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference owninguser { get; set; }

	[CsvHelper.Configuration.Attributes.Name("percentcomplete")]
	public System.Int32 percentcomplete { get; set; }

	[CsvHelper.Configuration.Attributes.Name("prioritycode")]
	public Microsoft.Xrm.Sdk.OptionSetValue prioritycode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("processid")]
	public System.Guid processid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("regardingobjectid")]
	public Microsoft.Xrm.Sdk.EntityReference regardingobjectid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("scheduleddurationminutes")]
	public System.Int32 scheduleddurationminutes { get; set; }

	[CsvHelper.Configuration.Attributes.Name("scheduledend")]
	public System.DateTime scheduledend { get; set; }

	[CsvHelper.Configuration.Attributes.Name("scheduledstart")]
	public System.DateTime scheduledstart { get; set; }

	[CsvHelper.Configuration.Attributes.Name("statecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue statecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("statuscode")]
	public Microsoft.Xrm.Sdk.OptionSetValue statuscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("subject")]
	public System.String subject { get; set; }

	[CsvHelper.Configuration.Attributes.Name("timezoneruleversionnumber")]
	public System.Int32 timezoneruleversionnumber { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_activitytypecode")]
	public string formatted_value_activitytypecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_actualdurationminutes")]
	public string formatted_value_actualdurationminutes { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_actualstart")]
	public string formatted_value_actualstart { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_createdby")]
	public string formatted_value_createdby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_createdon")]
	public string formatted_value_createdon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_isbilled")]
	public string formatted_value_isbilled { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_isregularactivity")]
	public string formatted_value_isregularactivity { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_isworkflowcreated")]
	public string formatted_value_isworkflowcreated { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_modifiedby")]
	public string formatted_value_modifiedby { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_modifiedon")]
	public string formatted_value_modifiedon { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_ownerid")]
	public string formatted_value_ownerid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_owningbusinessunit")]
	public string formatted_value_owningbusinessunit { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_percentcomplete")]
	public string formatted_value_percentcomplete { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_prioritycode")]
	public string formatted_value_prioritycode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_regardingobjectid")]
	public string formatted_value_regardingobjectid { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_scheduleddurationminutes")]
	public string formatted_value_scheduleddurationminutes { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_scheduledend")]
	public string formatted_value_scheduledend { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_scheduledstart")]
	public string formatted_value_scheduledstart { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_statecode")]
	public string formatted_value_statecode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_statuscode")]
	public string formatted_value_statuscode { get; set; }

	[CsvHelper.Configuration.Attributes.Name("formatted_value_timezoneruleversionnumber")]
	public string formatted_value_timezoneruleversionnumber { get; set; }

}
